# Generated by Django 5.2.7 on 2025-11-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(default='electrical', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='items_json',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
