# Generated by Django 5.2.7 on 2025-11-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_category_project_items_json_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='items_json',
        ),
        migrations.AddField(
            model_name='project',
            name='items',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
