# Generated by Django 5.2.7 on 2025-11-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_project_items_json_project_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='items',
        ),
        migrations.AddField(
            model_name='project',
            name='items_json',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
