# Generated by Django 5.2.8 on 2025-12-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_project_items_project_items_json_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfFormattedTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('template_file', models.FileField(upload_to='self_formatted_templates/')),
                ('custom_placeholders', models.TextField(blank=True, help_text='Lines like: MY_PLACEHOLDER = label text to search')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
