# Generated by Django 5.2.8 on 2025-12-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_selfformattedtemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selfformattedtemplate',
            name='custom_placeholders',
        ),
        migrations.AddField(
            model_name='selfformattedtemplate',
            name='placeholders',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
