# Generated by Django 5.2.8 on 2025-12-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_selfformattedtemplate_custom_placeholders_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selfformattedtemplate',
            name='placeholders',
        ),
        migrations.AddField(
            model_name='selfformattedtemplate',
            name='custom_placeholders',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='selfformattedtemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='selfformattedtemplate',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='selfformattedtemplate',
            name='template_file',
            field=models.FileField(upload_to='self_formatted'),
        ),
    ]
