# Generated by Django 5.2.8 on 2025-12-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_selfformattedtemplate_placeholders_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackendExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('electrical', 'Electrical'), ('civil', 'Civil')], max_length=20)),
                ('file', models.FileField(help_text='Upload the Excel file that contains Master Datas & Groups sheets.', upload_to='backend_excels/')),
                ('is_active', models.BooleanField(default=True, help_text='If multiple files exist, the newest active one is used.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
