# Generated by Django 5.2.8 on 2025-12-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_backendexcel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backendexcel',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='backendexcel',
            name='file',
            field=models.FileField(upload_to='backend_excels/'),
        ),
    ]
