# Generated by Django 5.2.8 on 2025-12-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_backendexcel_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackendWorkbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('electrical', 'Electrical'), ('civil', 'Civil')], max_length=20)),
                ('file', models.FileField(upload_to='backend_excels')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.DeleteModel(
            name='BackendExcel',
        ),
    ]
