# Generated by Django 4.2.27 on 2026-01-04 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_outputfile_upload_estimate_rate_snapshot_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('parse_estimate', 'Parse Estimate'), ('generate_bill', 'Generate Bill'), ('generate_workslip', 'Generate Workslip'), ('export_data', 'Export Data'), ('generate_output_excel', 'Generate Output Excel'), ('generate_estimate_excel', 'Generate Estimate Excel')], max_length=50),
        ),
    ]
