# Generated by Django 4.2.27 on 2026-01-04 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_increase_job_type_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('covering_letter', 'Covering Letter'), ('movement_slip', 'Movement Slip')], max_length=20)),
                ('name', models.CharField(help_text='A friendly name for this template', max_length=255)),
                ('file', models.FileField(upload_to='user_templates/')),
                ('is_active', models.BooleanField(default=True, help_text='Use this template for document generation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'template_type', 'is_active'], name='core_userdo_user_id_e2c135_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='userdocumenttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'template_type'), name='unique_active_template_per_user_type'),
        ),
    ]
