# Generated by Django 4.2.27 on 2026-01-15 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_add_user_document_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#6366f1', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_folders', to='core.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.workfolder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SavedWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Custom name for this saved work', max_length=255)),
                ('work_type', models.CharField(choices=[('new_estimate', 'New Estimate'), ('workslip', 'Workslip'), ('temporary_works', 'Temporary Works'), ('amc', 'AMC Module')], max_length=30)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('archived', 'Archived')], default='in_progress', max_length=20)),
                ('work_data', models.JSONField(default=dict)),
                ('category', models.CharField(default='electrical', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this work')),
                ('progress_percent', models.IntegerField(default=0)),
                ('last_step', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_works', to='core.workfolder')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_works', to='core.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_works', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workfolder',
            index=models.Index(fields=['organization', 'user'], name='core_workfo_organiz_10a717_idx'),
        ),
        migrations.AddIndex(
            model_name='workfolder',
            index=models.Index(fields=['parent'], name='core_workfo_parent__1a8611_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workfolder',
            unique_together={('organization', 'user', 'name', 'parent')},
        ),
        migrations.AddIndex(
            model_name='savedwork',
            index=models.Index(fields=['organization', 'user', '-updated_at'], name='core_savedw_organiz_ba9efc_idx'),
        ),
        migrations.AddIndex(
            model_name='savedwork',
            index=models.Index(fields=['work_type'], name='core_savedw_work_ty_39217e_idx'),
        ),
        migrations.AddIndex(
            model_name='savedwork',
            index=models.Index(fields=['folder'], name='core_savedw_folder__83a3c7_idx'),
        ),
        migrations.AddIndex(
            model_name='savedwork',
            index=models.Index(fields=['status'], name='core_savedw_status_9f21b9_idx'),
        ),
    ]
