# Generated by Django 4.2.27 on 2026-01-15 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_saved_works'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedwork',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent work this was generated from (e.g., Workslip from Estimate)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.savedwork'),
        ),
        migrations.AlterField(
            model_name='savedwork',
            name='work_type',
            field=models.CharField(choices=[('new_estimate', 'New Estimate'), ('workslip', 'Workslip'), ('bill', 'Bill'), ('temporary_works', 'Temporary Works'), ('amc', 'AMC Module')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='savedwork',
            index=models.Index(fields=['parent'], name='core_savedw_parent__5223e9_idx'),
        ),
    ]
