# Generated by Django 4.2.27 on 2026-01-24 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0002_add_multistate_sor_support'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0016_add_parent_to_savedwork'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backendworkbook',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Backend Workbook', 'verbose_name_plural': 'Backend Workbooks'},
        ),
        migrations.AddField(
            model_name='backendworkbook',
            name='financial_year',
            field=models.CharField(blank=True, help_text="Financial year like '2024-25'", max_length=20),
        ),
        migrations.AddField(
            model_name='backendworkbook',
            name='group_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='backendworkbook',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='backendworkbook',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Use as default for this category when no state specified'),
        ),
        migrations.AddField(
            model_name='backendworkbook',
            name='item_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='backendworkbook',
            name='name',
            field=models.CharField(blank=True, help_text="Descriptive name like 'TS Electrical SOR 2024-25'", max_length=255),
        ),
        migrations.AddField(
            model_name='backendworkbook',
            name='state',
            field=models.ForeignKey(blank=True, help_text='State this rate book applies to (leave blank for default/Telangana)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_workbooks', to='datasets.state'),
        ),
        migrations.AddField(
            model_name='backendworkbook',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_workbooks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='backendworkbook',
            name='category',
            field=models.CharField(choices=[('electrical', 'Electrical'), ('civil', 'Civil'), ('temp_electrical', 'Temp Electrical'), ('temp_civil', 'Temp Civil'), ('amc_electrical', 'AMC Electrical'), ('amc_civil', 'AMC Civil')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='backendworkbook',
            index=models.Index(fields=['category', 'state', 'is_active'], name='core_backen_categor_bd5ef4_idx'),
        ),
        migrations.AddIndex(
            model_name='backendworkbook',
            index=models.Index(fields=['category', 'is_default'], name='core_backen_categor_4e0b9d_idx'),
        ),
    ]
