# Generated by Django 4.2.27 on 2026-01-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_backendworkbook_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedwork',
            name='workslip_number',
            field=models.IntegerField(default=1, help_text='Workslip number for multi-workslip generation'),
        ),
    ]
