# Generated by Django 4.2.27 on 2026-01-29 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0018_add_workslip_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('government_name', models.CharField(blank=True, default='', max_length=255)),
                ('department_name', models.CharField(blank=True, default='', max_length=255)),
                ('officer_name', models.CharField(blank=True, default='', max_length=255)),
                ('officer_qualification', models.CharField(blank=True, default='', max_length=100)),
                ('officer_designation', models.CharField(blank=True, default='', max_length=255)),
                ('sub_division', models.CharField(blank=True, default='', max_length=255)),
                ('office_address', models.TextField(blank=True, default='')),
                ('recipient_designation', models.CharField(blank=True, default='', max_length=255)),
                ('recipient_division', models.CharField(blank=True, default='', max_length=255)),
                ('recipient_address', models.TextField(blank=True, default='')),
                ('office_code', models.CharField(blank=True, default='', max_length=100)),
                ('superior_designation', models.CharField(blank=True, default='', max_length=255)),
                ('copy_to_designation', models.CharField(blank=True, default='', max_length=255)),
                ('copy_to_section', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='letter_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Letter Settings',
                'verbose_name_plural': 'Letter Settings',
            },
        ),
    ]
