# Generated by Django 5.2.8 on 2026-02-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_lettersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocumenttemplate',
            name='file_data',
            field=models.BinaryField(blank=True, help_text='Template file content stored in DB for persistence', null=True),
        ),
        migrations.AddField(
            model_name='userdocumenttemplate',
            name='file_name',
            field=models.CharField(blank=True, default='', help_text='Original uploaded file name', max_length=255),
        ),
        migrations.AlterField(
            model_name='userdocumenttemplate',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='user_templates/'),
        ),
    ]
