# Generated by Django 5.2.8 on 2026-02-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_userdocumenttemplate_file_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedwork",
            name="bill_number",
            field=models.IntegerField(
                default=1, help_text="Bill number for multi-bill generation"
            ),
        ),
        migrations.AddField(
            model_name="savedwork",
            name="bill_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Bill type: first_part or first_final",
                max_length=50,
            ),
        ),
    ]
