# Generated by Django 5.2.8 on 2026-03-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_bill_number_and_bill_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfformattedtemplate',
            name='is_locked',
            field=models.BooleanField(default=True, help_text='Locked formats require confirmation to delete'),
        ),
        migrations.AddField(
            model_name='selfformattedtemplate',
            name='template_file_backup',
            field=models.BinaryField(blank=True, help_text='Database backup of template - survives file storage issues', null=True),
        ),
        migrations.AddField(
            model_name='selfformattedtemplate',
            name='template_file_name',
            field=models.CharField(blank=True, help_text='Original filename for backup', max_length=255),
        ),
        migrations.AddField(
            model_name='selfformattedtemplate',
            name='template_file_size',
            field=models.PositiveIntegerField(default=0, help_text='File size in bytes'),
        ),
    ]
