# Generated by Django 5.2.8 on 2026-05-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_add_template_persistence_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedwork',
            name='work_type',
            field=models.CharField(choices=[('new_estimate', 'Estimate'), ('workslip', 'Workslip'), ('bill', 'Bill'), ('temporary_works', 'Temporary Works'), ('amc', 'AMC Module')], max_length=30),
        ),
    ]
