# Generated by Django 5.2.8 on 2026-05-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_usergrouporder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergrouporder',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
