# Generated by Django 5.2.8 on 2026-06-12 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_savedwork_status_tracking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DwgTakeoff',
        ),
    ]
