# Generated by Django 5.2.8 on 2026-06-01 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_savedwork_status_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DwgTakeoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source_file', models.FileField(upload_to='dwg_uploads/%Y/%m/%d/')),
                ('source_format', models.CharField(default='dxf', max_length=8)),
                ('dxf_file', models.FileField(blank=True, null=True, upload_to='dwg_converted/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('converting', 'Converting DWG'), ('parsing', 'Parsing'), ('needs_review', 'Needs Review'), ('generating', 'Generating Excel'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('legend_map', models.JSONField(blank=True, default=dict)),
                ('zone_meta', models.JSONField(blank=True, default=list)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('result_file', models.FileField(blank=True, null=True, upload_to='dwg_results/%Y/%m/%d/')),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dwg_takeoffs', to='core.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dwg_takeoffs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='core_dwgtak_organiz_94ee06_idx'), models.Index(fields=['user', '-created_at'], name='core_dwgtak_user_id_f359b1_idx'), models.Index(fields=['status'], name='core_dwgtak_status_aadbfc_idx')],
            },
        ),
    ]
