# Generated by Django 5.2.8 on 2026-06-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_dwgtakeoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='dwgtakeoff',
            name='current_step',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='dwgtakeoff',
            name='inserts_cache',
            field=models.FileField(blank=True, null=True, upload_to='dwg_cache/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='dwgtakeoff',
            name='layer_filter',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dwgtakeoff',
            name='layouts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='dwgtakeoff',
            name='legend_bbox',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dwgtakeoff',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dwgtakeoff',
            name='warnings',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
