# Generated by Django 5.2.8 on 2026-06-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_dwgtakeoff_current_step_dwgtakeoff_inserts_cache_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dwgtakeoff',
            name='viewports',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
