# Generated by Django 5.2.8 on 2026-06-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_dwgtakeoff_viewports'),
    ]

    operations = [
        migrations.AddField(
            model_name='dwgtakeoff',
            name='linear_by_layer',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dwgtakeoff',
            name='linear_cache',
            field=models.FileField(blank=True, null=True, upload_to='dwg_cache/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='dwgtakeoff',
            name='linear_mapping',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dwgtakeoff',
            name='unit_scale',
            field=models.FloatField(default=1.0),
        ),
    ]
