# Generated by Django 5.2.8 on 2026-01-03 05:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(db_index=True, max_length=255)),
                ('identifier_type', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('ip', 'IP Address')], max_length=10)),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('failed_attempts', models.PositiveIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('lockout_count', models.PositiveIntegerField(default=0)),
                ('window_start', models.DateTimeField(auto_now_add=True)),
                ('last_request_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['identifier', 'identifier_type'], name='accounts_ot_identif_8411f5_idx'), models.Index(fields=['locked_until'], name='accounts_ot_locked__60d473_idx')],
                'unique_together': {('identifier', 'identifier_type')},
            },
        ),
        migrations.CreateModel(
            name='OTPToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10-15 digits with optional + prefix', regex='^\\+?[1-9]\\d{9,14}$')])),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('otp_code', models.CharField(max_length=6)),
                ('otp_hash', models.CharField(max_length=64)),
                ('otp_type', models.CharField(choices=[('login', 'Login'), ('verify_phone', 'Verify Phone'), ('verify_email', 'Verify Email'), ('reset_password', 'Reset Password')], default='login', max_length=20)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=5)),
                ('is_verified', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone', 'otp_type', 'is_verified'], name='accounts_ot_phone_71c7e3_idx'), models.Index(fields=['email', 'otp_type', 'is_verified'], name='accounts_ot_email_32f0ff_idx'), models.Index(fields=['expires_at'], name='accounts_ot_expires_4348db_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10-15 digits with optional + prefix', regex='^\\+?[1-9]\\d{9,14}$')])),
                ('phone_verified', models.BooleanField(default=False)),
                ('email_verified', models.BooleanField(default=False)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('designation', models.CharField(blank=True, max_length=255)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('country', models.CharField(default='India', max_length=100)),
                ('gstin', models.CharField(blank=True, help_text='15-character GST Identification Number', max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid 15-character GSTIN', regex='^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$')])),
                ('role', models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('user', 'User')], default='user', max_length=20)),
                ('profile_completed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('subscription_tier', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('notification_prefs', models.JSONField(blank=True, default=dict)),
                ('data_export_requested_at', models.DateTimeField(blank=True, null=True)),
                ('deletion_requested_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'indexes': [models.Index(fields=['phone'], name='accounts_us_phone_27e73a_idx'), models.Index(fields=['role'], name='accounts_us_role_e16858_idx'), models.Index(fields=['profile_completed'], name='accounts_us_profile_8fc929_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, unique=True)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('device_name', models.CharField(blank=True, max_length=255)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('os', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('user_agent', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='accounts_us_user_id_91ed82_idx'), models.Index(fields=['session_key'], name='accounts_us_session_511f42_idx'), models.Index(fields=['expires_at'], name='accounts_us_expires_3fa67a_idx')],
            },
        ),
    ]
