# Generated by Django 4.2.27 on 2026-01-24 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_add_module_backend'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBackendPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='subscriptions.modulebackend')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backend_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Backend Preference',
                'verbose_name_plural': 'User Backend Preferences',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'backend')},
            },
        ),
    ]
