# Generated by Django 5.2.8 on 2026-04-25 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_user_backend_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits (e.g. 9876543210)', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits (e.g. 9876543210)', regex='^\\d{10}$')]),
        ),
    ]
