# Generated by Django 5.2.8 on 2026-05-01 05:55

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_otptoken_phone_alter_userprofile_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCustomBackend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('file', models.FileField(upload_to=accounts.models._user_custom_backend_path)),
                ('category', models.CharField(choices=[('electrical', 'Electrical'), ('civil', 'Civil')], max_length=20)),
                ('applies_estimate', models.BooleanField(default=True)),
                ('applies_tempworks', models.BooleanField(default=False)),
                ('applies_amc', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_backends', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['user', 'category', 'is_active'], name='accounts_us_user_id_728164_idx')],
            },
        ),
    ]
