# Generated by Django 5.2.8 on 2026-05-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usercustombackend'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustombackend',
            name='group_name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='usercustombackend',
            name='units_override',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
