# Generated by Django 5.2.8 on 2026-01-03 06:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon class or emoji', max_length=50)),
                ('color', models.CharField(default='#3B82F6', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ Category',
                'verbose_name_plural': 'FAQ Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(help_text='Supports Markdown')),
                ('announcement_type', models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('danger', 'Critical'), ('maintenance', 'Maintenance'), ('feature', 'New Feature')], default='info', max_length=20)),
                ('target_audience', models.CharField(choices=[('all', 'All Users'), ('free', 'Free Users Only'), ('paid', 'Paid Users Only'), ('admin', 'Admins Only')], default='all', max_length=20)),
                ('target_modules', models.JSONField(blank=True, default=list, help_text='Show only for specific modules (empty = all)')),
                ('is_dismissible', models.BooleanField(default=True)),
                ('is_banner', models.BooleanField(default=False, help_text='Show as top banner (vs modal/toast)')),
                ('link_url', models.URLField(blank=True, help_text='Learn more link')),
                ('link_text', models.CharField(blank=True, default='Learn More', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('dismiss_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField(help_text='Supports Markdown')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords for search', max_length=500)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('helpful_count', models.PositiveIntegerField(default=0)),
                ('not_helpful_count', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on help homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='support.faqcategory')),
            ],
            options={
                'ordering': ['category', 'display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HelpGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('excerpt', models.TextField(blank=True, help_text='Short summary for listings', max_length=500)),
                ('content', models.TextField(help_text='Supports Markdown')),
                ('content_type', models.CharField(choices=[('article', 'Article'), ('tutorial', 'Tutorial'), ('video', 'Video'), ('release_notes', 'Release Notes')], default='article', max_length=20)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='help/images/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo URL')),
                ('related_module', models.CharField(blank=True, help_text='Module code this guide relates to', max_length=50)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help_guides', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guides', to='support.faqcategory')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General Inquiry'), ('billing', 'Billing & Payments'), ('technical', 'Technical Issue'), ('bug', 'Bug Report'), ('feature', 'Feature Request'), ('account', 'Account Issue'), ('data', 'Data/SSR Issue')], default='general', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('waiting_user', 'Waiting for User'), ('waiting_admin', 'Waiting for Admin'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('attachments', models.JSONField(blank=True, default=list, help_text='List of attachment file paths')),
                ('related_module', models.CharField(blank=True, max_length=50)),
                ('related_payment_id', models.CharField(blank=True, max_length=100)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('satisfaction_rating', models.PositiveIntegerField(blank=True, help_text='1-5 rating', null=True)),
                ('satisfaction_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_response_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_tickets', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin_reply', models.BooleanField(default=False)),
                ('message', models.TextField()),
                ('attachments', models.JSONField(blank=True, default=list, help_text='List of attachment file paths')),
                ('is_internal', models.BooleanField(default=False, help_text='Internal note (not visible to user)')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_messages', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.supportticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserDismissedAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dismissed_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissed_by_users', to='support.announcement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissed_announcements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['is_active', 'starts_at', 'ends_at'], name='support_ann_is_acti_47ee18_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['target_audience', 'is_active'], name='support_ann_target__834e97_idx'),
        ),
        migrations.AddIndex(
            model_name='faqitem',
            index=models.Index(fields=['category', 'is_published'], name='support_faq_categor_d82eb1_idx'),
        ),
        migrations.AddIndex(
            model_name='faqitem',
            index=models.Index(fields=['is_featured', 'is_published'], name='support_faq_is_feat_f070df_idx'),
        ),
        migrations.AddIndex(
            model_name='helpguide',
            index=models.Index(fields=['is_published', 'content_type'], name='support_hel_is_publ_e59b36_idx'),
        ),
        migrations.AddIndex(
            model_name='helpguide',
            index=models.Index(fields=['related_module', 'is_published'], name='support_hel_related_7dac66_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['user', 'status'], name='support_sup_user_id_1a6c3e_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status', 'priority'], name='support_sup_status_c67c70_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['assigned_to', 'status'], name='support_sup_assigne_87974a_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['ticket_number'], name='support_sup_ticket__4a7d4b_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketmessage',
            index=models.Index(fields=['ticket', 'created_at'], name='support_tic_ticket__0cd9bd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userdismissedannouncement',
            unique_together={('user', 'announcement')},
        ),
    ]
