# Generated by Django 5.2.8 on 2026-01-03 05:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text="Unique code like 'estimate', 'workslip', 'bill'", max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon class or emoji', max_length=50)),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color code', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('features', models.JSONField(blank=True, default=list, help_text='List of feature strings for display')),
                ('is_active', models.BooleanField(default=True)),
                ('is_free', models.BooleanField(default=False, help_text='Free for all users')),
                ('is_addon', models.BooleanField(default=False, help_text='Add-on module (not standalone)')),
                ('trial_days', models.PositiveIntegerField(default=7, help_text='Free trial period in days')),
                ('free_tier_limit', models.PositiveIntegerField(default=5, help_text='Number of free uses per month (0 = unlimited)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requires_modules', models.ManyToManyField(blank=True, help_text='Other modules required to use this module', related_name='required_by', to='subscriptions.module')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Coupon code (uppercase)', max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage'), ('fixed', 'Fixed Amount')], default='percent', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Max discount amount (for percentage coupons)', max_digits=10, null=True)),
                ('min_purchase', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum purchase amount', max_digits=10)),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='0 = unlimited')),
                ('max_uses_per_user', models.PositiveIntegerField(default=1, help_text='Max uses per user')),
                ('current_uses', models.PositiveIntegerField(default=0)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('first_purchase_only', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specific_users', models.ManyToManyField(blank=True, help_text='Leave empty for all users', to=settings.AUTH_USER_MODEL)),
                ('applicable_modules', models.ManyToManyField(blank=True, help_text='Leave empty for all modules', to='subscriptions.module')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModulePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_months', models.PositiveIntegerField(choices=[(1, '1 Month'), (3, '3 Months'), (6, '6 Months'), (12, '1 Year'), (24, '2 Years')], default=1)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Original price before discount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('sale_price', models.DecimalField(decimal_places=2, help_text='Actual selling price', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('gst_percent', models.DecimalField(decimal_places=2, default=Decimal('18.00'), help_text='GST percentage', max_digits=5)),
                ('usage_limit', models.PositiveIntegerField(default=0, help_text='Max uses per month (0 = unlimited)')),
                ('is_active', models.BooleanField(default=True)),
                ('is_popular', models.BooleanField(default=False, help_text="Show 'Popular' badge")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_options', to='subscriptions.module')),
            ],
            options={
                'ordering': ['module', 'duration_months'],
                'unique_together': {('module', 'duration_months')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.CharField(db_index=True, help_text='Internal order ID', max_length=100, unique=True)),
                ('pricing_snapshot', models.JSONField(default=dict, help_text='Snapshot of pricing at time of payment')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('gateway', models.CharField(choices=[('razorpay', 'Razorpay'), ('stripe', 'Stripe'), ('manual', 'Manual/Bank Transfer'), ('free', 'Free/Coupon')], default='razorpay', max_length=20)),
                ('gateway_order_id', models.CharField(blank=True, help_text='Order ID from payment gateway', max_length=255)),
                ('gateway_payment_id', models.CharField(blank=True, help_text='Payment ID from gateway (after success)', max_length=255)),
                ('gateway_signature', models.CharField(blank=True, help_text='Signature for verification', max_length=255)),
                ('gateway_response', models.JSONField(blank=True, default=dict, help_text='Full response from gateway')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], db_index=True, default='pending', max_length=20)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('refund_reason', models.TextField(blank=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('billing_name', models.CharField(blank=True, max_length=255)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('billing_phone', models.CharField(blank=True, max_length=20)),
                ('billing_address', models.TextField(blank=True)),
                ('billing_gstin', models.CharField(blank=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='subscriptions.coupon')),
                ('modules', models.ManyToManyField(help_text='Modules included in this payment', related_name='payments', to='subscriptions.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('invoice_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_items', models.JSONField(default=list)),
                ('billing_name', models.CharField(max_length=255)),
                ('billing_address', models.TextField()),
                ('billing_gstin', models.CharField(blank=True, max_length=15)),
                ('billing_state', models.CharField(blank=True, max_length=100)),
                ('seller_name', models.CharField(default='Your Company Name', max_length=255)),
                ('seller_address', models.TextField(default='Your Company Address')),
                ('seller_gstin', models.CharField(blank=True, max_length=15)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/%Y/%m/')),
                ('is_paid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='subscriptions.payment')),
            ],
            options={
                'ordering': ['-invoice_date', '-invoice_number'],
            },
        ),
        migrations.CreateModel(
            name='UserModuleSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], db_index=True, default='trial', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('usage_limit', models.PositiveIntegerField(default=0, help_text='0 = unlimited')),
                ('usage_reset_at', models.DateTimeField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('renewal_reminder_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.module')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='subscriptions.payment')),
                ('pricing', models.ForeignKey(blank=True, help_text='Null for trial/free subscriptions', null=True, on_delete=django.db.models.deletion.PROTECT, to='subscriptions.modulepricing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='What action was performed (generate_estimate, download_pdf, etc.)', max_length=100)),
                ('resource_id', models.CharField(blank=True, help_text='ID of the resource created/modified', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='subscriptions.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to='subscriptions.usermodulesubscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'status'], name='subscriptio_user_id_9c57a2_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order_id'], name='subscriptio_order_i_4a6d6c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['gateway_order_id'], name='subscriptio_gateway_7a809f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='subscriptio_created_395e39_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['user', 'invoice_date'], name='subscriptio_user_id_60b010_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='subscriptio_invoice_50e7d3_idx'),
        ),
        migrations.AddIndex(
            model_name='usermodulesubscription',
            index=models.Index(fields=['user', 'module', 'status'], name='subscriptio_user_id_b6dd20_idx'),
        ),
        migrations.AddIndex(
            model_name='usermodulesubscription',
            index=models.Index(fields=['expires_at'], name='subscriptio_expires_b34e52_idx'),
        ),
        migrations.AddIndex(
            model_name='usermodulesubscription',
            index=models.Index(fields=['status', 'expires_at'], name='subscriptio_status_ed48be_idx'),
        ),
        migrations.AddIndex(
            model_name='usagelog',
            index=models.Index(fields=['user', 'module', 'created_at'], name='subscriptio_user_id_045996_idx'),
        ),
        migrations.AddIndex(
            model_name='usagelog',
            index=models.Index(fields=['module', 'action', 'created_at'], name='subscriptio_module__73a130_idx'),
        ),
    ]
