# Generated by Django 5.2.8 on 2026-01-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='url_name',
            field=models.CharField(blank=True, help_text="Django URL name for this module (e.g., 'datas', 'tempworks_home')", max_length=100),
        ),
        migrations.AlterField(
            model_name='module',
            name='trial_days',
            field=models.PositiveIntegerField(default=1, help_text='Free trial period in days (1 day per user)'),
        ),
    ]
