# Generated by Django 5.2.8 on 2026-01-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_add_url_name_to_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='backend_sheet_file',
            field=models.FileField(blank=True, help_text='Custom backend Excel file for this module', null=True, upload_to='module_backends/'),
        ),
        migrations.AddField(
            model_name='module',
            name='backend_sheet_name',
            field=models.CharField(blank=True, help_text="Custom name for backend sheet (e.g., 'amc_electrical', 'amc_civil')", max_length=100),
        ),
    ]
