# Generated by Django 4.2.27 on 2026-01-24 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_add_backend_sheet_to_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleBackend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('electrical', 'Electrical'), ('civil', 'Civil')], db_index=True, max_length=20)),
                ('name', models.CharField(help_text="Name for this backend (e.g., 'Telangana SOR 2024-25', 'AP Electrical Rates')", max_length=255)),
                ('code', models.CharField(blank=True, help_text="Short code (e.g., 'TS_2024', 'AP_2024')", max_length=50)),
                ('description', models.TextField(blank=True, help_text='Optional description or notes')),
                ('file', models.FileField(help_text="Excel file with 'Master Datas' and 'Groups' sheets", upload_to='module_backends/')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in dropdown (lower appears first)')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text="Use as default when user hasn't selected a specific backend")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backends', to='subscriptions.module')),
            ],
            options={
                'verbose_name': 'Module Backend',
                'verbose_name_plural': 'Module Backends',
                'ordering': ['module', 'category', 'display_order', 'name'],
                'indexes': [models.Index(fields=['module', 'category', 'is_active'], name='subscriptio_module__fa9945_idx'), models.Index(fields=['module', 'is_default'], name='subscriptio_module__c3b395_idx')],
            },
        ),
    ]
