# Generated by Django 5.2.8 on 2026-03-07 14:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_modulebackend_file_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='All Modules Bundle', max_length=100)),
                ('description', models.TextField(blank=True, default='Get access to all modules at a special bundled price.')),
                ('icon', models.CharField(default='stack', help_text='Bootstrap icon name', max_length=50)),
                ('color', models.CharField(default='#8b5cf6', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('features', models.JSONField(blank=True, default=list, help_text='Feature strings for display')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modules', models.ManyToManyField(help_text='Modules included in this bundle', related_name='bundles', to='subscriptions.module')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BundlePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_months', models.PositiveIntegerField(choices=[(1, '1 Month'), (3, '3 Months'), (6, '6 Months'), (12, '1 Year'), (24, '2 Years')], default=1)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Original price (can be sum of individual modules or any reference)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('sale_price', models.DecimalField(decimal_places=2, help_text='Actual bundle selling price', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('gst_percent', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_pricing', to='subscriptions.modulebundle')),
            ],
            options={
                'ordering': ['bundle', 'duration_months'],
                'unique_together': {('bundle', 'duration_months')},
            },
        ),
    ]
