# Generated by Django 5.2.8 on 2026-03-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_modulebundle_bundlepricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='max_usage_per_subscription',
            field=models.IntegerField(default=-1, help_text='Max times a user can use this module per subscription. -1 = unlimited, 0 = disabled'),
        ),
        migrations.AddField(
            model_name='module',
            name='trial_hours',
            field=models.PositiveIntegerField(default=0, help_text='Additional trial hours (added to trial_days)'),
        ),
        migrations.AlterField(
            model_name='module',
            name='trial_days',
            field=models.PositiveIntegerField(default=1, help_text='Free trial period in days'),
        ),
    ]
