# Generated by Django 5.2.8 on 2026-04-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_add_trial_hours_and_usage_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='payments_enabled',
            field=models.BooleanField(default=False, help_text='Show payment/subscription options to users. Uncheck to hide pricing and only show trials.'),
        ),
    ]
