# Generated by Django 5.2.8 on 2026-05-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_module_payments_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('razorpay', 'Razorpay')], default='razorpay', max_length=20)),
                ('event_id', models.CharField(db_index=True, max_length=255)),
                ('event_type', models.CharField(blank=True, max_length=100)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('succeeded', models.BooleanField(default=False)),
                ('payload_sha256', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'indexes': [models.Index(fields=['gateway', 'event_id'], name='subscriptio_gateway_9e164b_idx'), models.Index(fields=['received_at'], name='subscriptio_receive_6f800a_idx')],
                'constraints': [models.UniqueConstraint(fields=('gateway', 'event_id'), name='uniq_gateway_event')],
            },
        ),
    ]
